[project]
name = "hans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyaudio>=0.2.14",
    "pywhispercpp",
]

[tool.uv.sources]
pywhispercpp = { git = "https://github.com/absadiki/pywhispercpp" }
