from __future__ import annotations
from numpy.typing import NDArray
import numpy as np

class WhisperContext: ...

class ParsedGrammar: ...

def grammar_parse(grammar: str) -> ParsedGrammar: ...

def context_init(model_path: str) -> WhisperContext: ...

def context_free(ctx: WhisperContext) -> None: ...

def transcribe(ctx: WhisperContext, samples: NDArray[np.float32], initial_prompt: str, gbnf_grammar: str, grammar_rule: str) -> str: ...
