[project]
name = "gtfs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sam Burba", email = "github@samburba.com" }
]
requires-python = ">=3.11.10"
dependencies = [
    "aiocsv>=1.3.2",
    "aiodns>=3.2.0",
    "aiofiles>=24.1.0",
    "aiohttp>=3.11.11",
    "aiosqlite>=0.21.0",
    "gtfsdb>=0.6.0",
    "stream-unzip>=0.0.99",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
